const mainFullpage = new fullpage("#fullpage", {
  anchors: [
    "page1",
    "page2",
    "page3",
    "page4",
    "page5",
    "page6",
    "page7",
    "page8",
  ],
  sectionsColor: [
    "#FFFFFF",
    "#FF976A",
    "#FFFFFF",
    "#FFFFFF",
    "#FFFFFF",
    "#000000",
    "#000000",
    "#000000",
  ],
  navigation: true,
  controlArrowColor: "#000000",
  // responsiveWidth: 1000,
});
